import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

export const metadata: Metadata = {
  title: "interactive map",
  description: "Generated by create next app",
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout({ children }: Props) {

  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
           {children}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
